name: Tests
on:
  push:
    branches:
    - master

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-18.04, macos-latest, windows-latest]
        go: ['1.13', '1.14']

    name: Test on ${{ matrix.os }} with Go ${{ matrix.go }}
    runs-on: ${{ matrix.os }}
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Run Tests
      run: make clean test
